services:
  - type: worker
    name: KingLegenPro
    runtime: python
    pythonVersion: 3.10.12   # âœ… downgrade to 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
